### ISSUE TITLE
Issue with resourceExist logic

### ISSUE THREAD

**Issue by jcoveney** [Cascading/cascading-jdbc#13]
Related to https://github.com/Cascading/cascading-jdbc/issues/12

The issue is this: https://github.com/Cascading/cascading-jdbc/blob/2.5/cascading-jdbc-core/src/main/java/cascading/jdbc/JDBCTap.java#L671-L680

Since it just catches exception, in the case of a default table exists query and then some other transient issue on the database. For example, a long running query on the same table could have a lock on the table and cause this query to time out, which would then make this think that the table exists. I realize that this is kind of an edge case but this led to a production table being dropped.

**Comment by fs111** [comment]
Closing this after the change in #17

**Comment by jcoveney** [comment]
This is actually still an issue. The two are related, but this can still happen.

**Comment by fs111** [comment]
I am a bit lost here. How can this cause issues. We are rethrowing the SQLException as an IOExeption and that should stop your program. I am most likely missing something here though.

**Comment by jcoveney** [comment]
I can dig up the support ticket we filed about it tomorrow or you can look
up the ones wih my name on it if you have access.

**Comment by fs111** [comment]
closing. If this is still an issue, please file a new bug.
