### ISSUE TITLE
exception handling bug

### ISSUE THREAD

**Issue by derrickpelletier** [Cascading/cascading-jdbc#15]
In https://github.com/Cascading/cascading-jdbc/blob/2.5/cascading-jdbc-core/src/main/java/cascading/jdbc/db/DBOutputFormat.java#L135

An exception is created without a message which leads to a NullPointer when trying to `substring` the exception's message.

I'm also throwing together a test case for how I even got this in the first place, see:
https://groups.google.com/forum/#!topic/cascading-user/nZ-xRtEDGpI

```
Error: java.lang.NullPointerException
    at cascading.jdbc.db.DBOutputFormat.manageBatchProcessingError(DBOutputFormat.java:158)
    at cascading.jdbc.db.DBOutputFormat.executeBatch(DBOutputFormat.java:136)
```

**Comment by fs111** [comment]
Can you try with cascading-jdbc-postgresql 2.5.3-wip-75?
