### ISSUE TITLE
Cascading exception  java.lang.IllegalArgumentException: Source fields not found in sinked data.

### ISSUE THREAD

**Issue by velkumar0505** [Cascading/cascading-jdbc#24]
Iam reading a binary file in Cascading and write it to a text file. 

Pipe testRecords = new Pipe("Test records");
            Fields fieldSelector = new Fields(PotentialCounterfeitDatum.TRANSIT_ABA_FN, PotentialCounterfeitDatum.ACCOUNT_NUMBER_FN, PotentialCounterfeitDatum.AMOUNT_FN,
                    PotentialCounterfeitDatum.SCHEME_CREATE_DATE_FN);
            testRecords =  new Retain(testRecords, fieldSelector);

 Iam getting an exception (java.lang.IllegalArgumentException: Source fields not found in sinked data).

Please advise what may be the error

**Comment by fs111** [comment]
Hi,

this seems to not have to do much with cascading-jdbc. Please join our mailing list and explain your problem with all relevant code parts and full stack trace there: https://groups.google.com/forum/#!forum/cascading-user

I am closing this issue, since it has nothing to do with cascading-jdbc.
